openapi: 3.1.0
info:
  title: Money Book API Server
  version: '1.0'
  summary: Money Book API Server.
  contact:
    name: Calvin C. Chan
    email: hello@calvin-c.com
servers:
  - url: 'http://localhost:50420'
    description: Local
paths:
  '/months/{id}':
    get:
      summary: Get Month
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Month'
      operationId: get-months-id
      description: Get a month summary document.
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Month ID in YYYY-MM format
  '/transactions/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Transaction ID
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
      operationId: get-transactions-id
      description: ''
    patch:
      summary: ''
      operationId: patch-transactions-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: number
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction__edit'
    delete:
      summary: ''
      operationId: delete-transactions-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: number
components:
  schemas:
    Month:
      type: object
      x-examples:
        example-1:
          _id: 100
          year: 2022
          month: 4
          openingBalance: 0
          closingBalance: -422400
          value: -422400
          dateFrom: '2022-03-31T16:00:00.000Z'
          dateTo: '2022-04-30T15:59:59.999Z'
          days:
            - day: 1
              value: -300000
            - day: 2
              value: 0
            - day: 3
              value: 0
            - day: 4
              value: 0
            - day: 5
              value: 0
            - day: 6
              value: 0
            - day: 7
              value: 0
            - day: 8
              value: 0
            - day: 9
              value: 0
            - day: 10
              value: 0
            - day: 11
              value: 0
            - day: 12
              value: 0
            - day: 13
              value: 0
            - day: 14
              value: -100
            - day: 15
              value: 0
            - day: 16
              value: 0
            - day: 17
              value: 0
            - day: 18
              value: 0
            - day: 19
              value: 0
            - day: 20
              value: 0
            - day: 21
              value: 0
            - day: 22
              value: 0
            - day: 23
              value: 0
            - day: 24
              value: 0
            - day: 25
              value: 0
            - day: 26
              value: -12300
            - day: 27
              value: -110000
            - day: 28
              value: 0
            - day: 29
              value: 0
            - day: 30
              value: 0
          createdAt: '2022-04-26T13:34:37.163Z'
          updatedAt: '2022-04-26T23:35:22.955Z'
          __v: 0
      properties:
        year:
          type: number
          description: Year ID
        month:
          type: number
          description: Month ID
        openingBalance:
          type: number
          description: Opening balance of the month
        closingBalance:
          type: number
          description: Closing balance of the month
        value:
          type: number
          description: Total value of all transactions in the month
        dateFrom:
          type: string
          description: Start date of the month
          format: date-time
        dateTo:
          type: string
          description: End date of the month
          format: date-time
        days:
          type: array
          uniqueItems: true
          description: Day summary
          items:
            type: object
            properties:
              day:
                type: number
                description: Day of month (base-1)
              value:
                type: number
                description: Total value of all transactions of the day
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Transaction:
      description: ''
      type: object
      x-examples:
        example-1:
          _id: 1024
          value: -300000
          label: Ticket
          confirmed: false
          transactionDate: '2022-04-01T14:25:19.139Z'
          description: ''
          createdAt: '2022-04-26T14:25:31.895Z'
          updatedAt: '2022-04-26T16:37:34.344Z'
          __v: 0
      properties:
        _id:
          type: number
        value:
          type: number
        label:
          type: string
        confirmed:
          type: boolean
        transactionDate:
          type: string
        description:
          type: string
      required:
        - value
        - transactionDate
    Transaction__edit:
      description: ''
      type: object
      x-examples:
        example-1:
          _id: 1024
          value: -300000
          label: Ticket
          confirmed: false
          transactionDate: '2022-04-01T14:25:19.139Z'
          description: ''
          createdAt: '2022-04-26T14:25:31.895Z'
          updatedAt: '2022-04-26T16:37:34.344Z'
          __v: 0
      title: Transaction__edit
      properties:
        value:
          type: number
        label:
          type: string
        confirmed:
          type: boolean
        transactionDate:
          type: string
        description:
          type: string
      required:
        - value
        - transactionDate
